"""update1

Revision ID: 69ffdec0a9ae
Revises: d451f0bda051
Create Date: 2023-03-08 12:32:17.414388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ffdec0a9ae'
down_revision = 'd451f0bda051'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
